name: 'hollywood'
version: '1.0'
config-version: 2
profile: normalize
model-paths: ["models"]
docs-paths: ["docs"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets:
- build
quoting:
  database: true
  schema: false
  identifier: true
models:
  dbt_project:
    with_full_name:
      +materialized: table
