name: airbyte_utils
version: '1.0'
config-version: 2
profile: normalize
model-paths: ["models"]
docs-paths: ["docs"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
packages-install-path: ./dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  dbt_project:
    materialized: table
